# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c3a22ab7a0acb7475c6138b3393e75886cb7ff02e71b34b7d758e5cbf9b8be9f6f68e464d416ace480b6162822acff38ae9a196fc2555d9383bfd8bce598c1

test:
  secret_key_base: df5b59442bb1fcc1d57cfe33b18b926e57307643f7b4d578deb7d9dab48e6978460f34bd4e5ec83ed2d6f98e7c0f0fc7a40e2d776b69ccf83d464be7d784e580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
